engines:
  balancedEngine:
    type: multiplyingEngine
    material: sugar cane
    name: '&2Balanced Engine'
    lore:
    - '&bMedium speed, acceleration and fuel.'
    - '&aHold shift to accelerate.'
    max_speed: 1.5
    min_speed: 0.75
    acceleration: 0.025
    max_fuel: 750
    consumption: 2
    regeneration: 1
    glow_time: 100
  fastEngine:
    type: multiplyingEngine
    material: feather
    name: '&2Fast Engine'
    lore:
    - '&bHigh maximum speed and fuel regeneration.'
    - '&bLow acceleration and fuel reserves.'
    - '&aHold shift to accelerate.'
    max_speed: 2.5
    min_speed: 0.5
    acceleration: 0.0125
    max_fuel: 500
    consumption: 2.5
    regeneration: 1.5
    glow_time: 50
  strongEngine:
    type: multiplyingEngine
    material: wheat
    name: '&2Strong Engine'
    lore:
    - '&bLow speed and fuel regeneration.'
    - '&bHigh acceleration and fuel reserves.'
    - '&aHold shift to accelerate.'
    max_speed: 1
    min_speed: 1
    acceleration: 0.05
    max_fuel: 1500
    consumption: 2
    regeneration: 1
    glow_time: 200
wings:
  balancedWings:
    type: simpleWings
    material: elytra
    name: '&3Balanced Wings'
    lore:
    - '&bDefault Elytra fight.'
    - '&bMedium durability.'
    - '&aPress space while falling to fly.'
    max_health: 2800
    regeneration: 0.5
    aerodynamics: 0
    liftingforce: 0
    maxLift: 0
  lightWings:
    type: simpleWings
    material: elytra
    name: '&3Light Wings'
    lore:
    - '&bFast wings with strong lifting force.'
    - '&bQuite fragile.'
    - '&aPress space while falling to fly.'
    max_health: 2000
    regeneration: 0.5
    aerodynamics: 0.002
    liftingforce: 0.001
    maxLift: 0.01
  heavyWings:
    type: simpleWings
    material: elytra
    name: '&3Heavy Wings'
    lore:
    - '&bSlow, heavy wings.'
    - '&bVery sturdy.'
    - '&aPress space while falling to fly.'
    max_health: 3600
    regeneration: 0.5
    aerodynamics: -0.0025
    liftingforce: 0
    maxLift: 0
    weight: 0.01
actions:
  balancedShot:
    type: machineGun
    entity: small fireball
    burst_amount: 10
    burst_ticks: 1
    projectile_speed: 5.75
    damage: 1200
    wings_off: true
    kills_on_ground: false
    friendly_fire: true
    suicidal: false
    physical_damage: 7.5
  strongShot:
    type: machineGun
    entity: fireball
    burst_amount: 10
    burst_ticks: 1
    projectile_speed: 5
    damage: 2800
    wings_off: true
    kills_on_ground: true
    friendly_fire: true
    suicidal: false
    physical_damage: 10
  fastShot:
    type: machineGun
    entity: snowball
    burst_amount: 10
    burst_ticks: 2
    projectile_speed: 50
    damage: 700
    wings_off: false
    kills_on_ground: false
    friendly_fire: true
    suicidal: false
    physical_damage: 5
  gunShot:
    type: machineGun
    entity: snowball
    burst_amount: 1
    burst_ticks: 1
    projectile_speed: 5
    damage: 1000
    wings_off: false
    kills_on_ground: false
    friendly_fire: true
    suicidal: false
    physical_damage: 5
  missile:
    type: homingMissile
    entity: arrow
    search_range: 64
    search_radius: 0.1
    speed: 3
    lifetime: 600
    maneuverability: 1
    damage: 2000
    wings_off: true
    kills_on_ground: false
    friendly_fire: true
    suicidal: true
    physical_damage: 18
  launch:
    type: launcher
    speed: 2
  giveMoney:
    money: 5
    type: money
  repair:
    type: wingsHealth
    amount: 1
  target:
    type: targetCompass
    target: hostile
  fixAll:
    type: wingsHealth
    amount: 4000
  refuel:
    type: fuel
    amount: 2000
activators:
  left:
    type: leftClick
  right:
    type: rightClick
  slow:
    type: slowTick
  wingsDead:
    type: wingsHealth
    min: 0
items:
  balancedWeapon:
    material: bone
    name: '&4Balanced Weapon'
    lore:
    - '&bMedium burst length, low damage.'
    - '&bDisables wings.'
    - '&aLeft click to shoot, right click to reload.'
    slot: 0
    ammo: 10
    usages:
      shoot:
        where: air
        cooldown: 30
        ammo_use: 1
        activators:
        - left
        actions:
        - balancedShot
      reload:
        where: no fall
        cooldown: 150
        ammo_use: -10
        activators:
        - right
  strongWeapon:
    material: blaze rod
    name: '&4Strong Weapon'
    lore:
    - '&bShort burst length, high damage.'
    - '&bDisables wings, kills on ground.'
    - '&aLeft click to shoot, right click to reload.'
    slot: 0
    ammo: 15
    usages:
      shoot:
        where: air
        cooldown: 40
        ammo_use: 1
        activators:
        - left
        actions:
        - strongShot
      reload:
        where: no fall
        cooldown: 200
        ammo_use: -15
        activators:
        - right
  fastWeapon:
    material: stick
    name: '&4Fast Weapon'
    lore:
    - '&bLong burst length, medium damage.'
    - '&aLeft click to shoot, right click to reload.'
    slot: 0
    ammo: 5
    usages:
      shoot:
        where: air
        cooldown: 20
        ammo_use: 1
        activators:
        - left
        actions:
        - fastShot
      reload:
        where: no fall
        cooldown: 100
        ammo_use: -5
        activators:
        - right
  gun:
    material: torch
    name: '&4Gun'
    lore:
    - '&bCan shoot from the ground.'
    - '&aLeft click to shoot, right click to reload.'
    slot: 2
    ammo: 10
    usages:
      shoot:
        where: no air
        cooldown: 5
        ammo_use: 1
        activators:
        - left
        actions:
        - gunShot
      reload:
        where: no fall
        cooldown: 50
        ammo_use: -10
        activators:
        - right
  rocket:
    material: arrow
    name: '&eRocket'
    lore:
    - '&bTracks players. Disables wings. High damage.'
    - '&aLeft click to launch.'
    slot: 3
    consumable: true
    usages:
      shoot:
        where: air
        cooldown: 100
        activators:
        - left
        actions:
        - missile
  radar:
    material: compass
    name: '&aRadar'
    lore:
    - '&bShows nearby hostiles.'
    - '&aNo need to hold or click it.'
    slot: 8
    usages:
      passive:
        activators:
        - slow
        actions:
        - target
  launcher:
    material: firework
    name: '&5Launcher'
    lore:
    - '&bLaunches you in the direction you''re looking.'
    - '&aLeft click to use.'
    slot: 4
    consumable: true
    usages:
      shoot:
        cooldown: 50
        activators:
        - left
        actions:
        - launch
  wings:
    material: water lily
    name: '&dEmergency Wings'
    lore:
    - '&bRestores destroyed wings.'
    - '&aLeft click to use.'
    slot: 5
    consumable: true
    usages:
      use:
        where: ground
        activators:
        - left
        - wingsDead
        actions:
        - repair
lobbies:
  default:
    type: fixedPhysicalLobby
    join:
    - -5188;93;4537;void
    spawn: -5191.5;92;4537.5;void;90;0
    start: -5200;93;4537;void
    leave: -5190;93;4537;void
    default_class:
    - balanced
    items:
      addRocket:
        type: add
        buy_cost: 15
        block: -5198;93;4534;void
        items:
        - item: rocket
          max: 6
      addLauncher:
        type: add
        buy_cost: 10
        block: -5196;93;4534;void
        items:
        - item: launcher
          max: 3
      addCompass:
        type: add
        buy_cost: 5
        block: -5194;93;4534;void
        items:
        - item: radar
          max: 1
      emergencyWings:
        type: add
        buy_cost: 20
        block: -5192;93;4534;void
        items:
        - item: wings
          max: 1
      fast:
        name: Fast
        type: replace
        block: -5197;93;4540;void
        engine: fastEngine
        wings: lightWings
        items:
        - item: fastWeapon
        - item: gun
      balanced:
        name: Balanced
        type: replace
        block: -5195;93;4540;void
        engine: balancedEngine
        wings: balancedWings
        items:
        - item: balancedWeapon
        - item: gun
      strong:
        name: Strong
        type: replace
        block: -5193;93;4540;void
        engine: strongEngine
        wings: heavyWings
        items:
        - item: strongWeapon
        - item: gun
    respawn_action: save
    games:
    - default
games:
  default:
    type: teamDeathMatch
    points_to_win: 25
    teams:
      blue:
        name: 'Blue'
        location: -5194.5;200;4665.5;void;180;0
        color: blue
      red:
        name: 'Red'
        location: -5194.5;200;4409.5;void;0;0
        color: red
    money:
      enabled: true
      enemy_hit: 1
      enemy_kill: 5
      friendly_kill: -2
      by_friendly_death: 2
      suicide: -1
    height_limit: 512
    height_damage: 0.5
    bonuses:
    - money
    - fix
    center: -5194.5;200;4537.5;void
    radius: 1000
bonuses:
  money:
    type: entity
    location: -5167.5;125.5;4537.5;void
    entity: sheep
    distance: 2
    consumable: true
    cooldown: 600
    respawn: 600
    actions:
    - giveMoney
  fix:
    type: entity
    location: -5282.5;159;4537.5;void
    entity: chicken
    distance: 2.5
    consumable: true
    cooldown: 1200
    respawn: 1200
    actions:
    - fixAll
    - refuel
