engines:
  balancedEngine:
    type: multiplyingEngine
    material: sugar cane
    name: '&2Balanced Engine'
    lore:
    - '&bMedium speed, acceleration and fuel.'
    - '&aHold shift to accelerate.'
    max_speed: 1.5
    min_speed: 0.75
    acceleration: 0.025
    max_fuel: 750
    consumption: 2
    regeneration: 1
    glow_time: 100
    weight: 0
  fastEngine:
    type: multiplyingEngine
    material: feather
    name: '&2Fast Engine'
    lore:
    - '&bHigh maximum speed and fuel regeneration.'
    - '&bLow acceleration and fuel reserves.'
    - '&aHold shift to accelerate.'
    max_speed: 2.5
    min_speed: 0.5
    acceleration: 0.01
    max_fuel: 500
    consumption: 2.5
    regeneration: 1.5
    glow_time: 50
    weight: 0
  strongEngine:
    type: multiplyingEngine
    material: wheat
    name: '&2Strong Engine'
    lore:
    - '&bLow speed and fuel regeneration.'
    - '&bHigh acceleration and fuel reserves.'
    - '&aHold shift to accelerate.'
    max_speed: 1
    min_speed: 1
    acceleration: 0.05
    max_fuel: 1500
    consumption: 2
    regeneration: 1
    glow_time: 200
    weight: 0
wings:
  balancedWings:
    type: simpleWings
    material: elytra
    name: '&3Balanced Wings'
    lore:
    - '&bDefault Elytra fight.'
    - '&bMedium durability.'
    - '&aPress space while falling to fly.'
    max_health: 2400
    regeneration: 0.5
    aerodynamics: 0
    liftingforce: 0
    maxLift: 0
    weight: 0
  lightWings:
    type: simpleWings
    material: elytra
    name: '&3Light Wings'
    lore:
    - '&bFast wings with strong lifting force.'
    - '&bQuite fragile.'
    - '&aPress space while falling to fly.'
    max_health: 1800
    regeneration: 0.5
    aerodynamics: 0.0025
    liftingforce: 0.001
    maxLift: 0
    weight: 0
  heavyWings:
    type: simpleWings
    material: elytra
    name: '&3Heavy Wings'
    lore:
    - '&bSlow, heavy wings.'
    - '&bVery sturdy.'
    - '&aPress space while falling to fly.'
    max_health: 3600
    regeneration: 0.5
    aerodynamics: -0.0025
    liftingforce: 0
    maxLift: 0
    weight: 0.002
items:
  balancedWeapon:
    type: machineGun
    material: bone
    name: '&4Balanced Weapon'
    lore:
    - '&bMedium burst length, low damage.'
    - '&bDisables wings.'
    - '&aLeft click to shoot.'
    entity: small fireball
    slot: 0
    burst_amount: 15
    burst_ticks: 1
    projectile_speed: 5.75
    cooldown: 35
    consumable: false
    only_air: true
    damage: 601
    wings_off: true
    kills_on_ground: false
    friendly_fire: true
    suicidal: false
    physical_damage: 7.5
    weight: 0
  strongWeapon:
    type: machineGun
    material: blaze rod
    name: '&4Strong Weapon'
    lore:
    - '&bShort burst length, high damage.'
    - '&bDisables wings, kills on ground.'
    - '&aLeft click to shoot.'
    entity: fireball
    slot: 0
    burst_amount: 10
    burst_ticks: 1
    projectile_speed: 5
    cooldown: 40
    consumable: false
    only_air: true
    damage: 2401
    wings_off: true
    kills_on_ground: true
    friendly_fire: true
    suicidal: false
    physical_damage: 10
    weight: 0
  fastWeapon:
    type: machineGun
    material: stick
    name: '&4Fast Weapon'
    lore:
    - '&bLong burst length, medium damage.'
    - '&aLeft click to shoot.'
    entity: snowball
    slot: 0
    burst_amount: 20
    burst_ticks: 1
    projectile_speed: 50
    cooldown: 25
    consumable: false
    only_air: true
    damage: 901
    wings_off: false
    kills_on_ground: false
    friendly_fire: true
    suicidal: false
    physical_damage: 5
    weight: 0
  gun:
    type: machineGun
    material: torch
    name: '&4Gun'
    lore:
    - '&bCan shoot from the ground.'
    - '&aLeft click to shoot.'
    entity: snowball
    slot: 2
    burst_amount: 1
    burst_ticks: 1
    projectile_speed: 5
    cooldown: 5
    consumable: false
    only_air: false
    damage: 1001
    wings_off: false
    kills_on_ground: false
    friendly_fire: true
    suicidal: false
    physical_damage: 5
    weight: 0
  rocket:
    type: homingMissile
    material: arrow
    name: '&eRocket'
    lore:
    - '&bTracks players. Disables wings. High Damage.'
    - '&aLeft click to launch.'
    entity: arrow
    slot: 3
    search_range: 64
    search_radius: 0.05
    speed: 3
    lifetime: 600
    maneuverability: 0.1
    cooldown: 0
    consumable: true
    only_air: true
    damage: 2001
    wings_off: true
    kills_on_ground: false
    friendly_fire: true
    suicidal: true
    physical_damage: 18
    weight: 0
  radar:
    type: vanillaItem
    material: compass
    name: '&aRadar'
    lore:
    - '&bShows nearby hostiles.'
    - '&aNo need to hold or click it.'
    slot: 8
    passive_effects:
    - radar
    weight: 0
  launcher:
    type: launcher
    material: firework
    name: '&5Launcher'
    lore:
    - '&bLaunches you in the direction you''re looking.'
    - '&aLeft click to use.'
    slot: 4
    speed: 2
    cooldown: 100
    consumable: true
    only_air: false
    weight: 0
effects:
  radar:
    type: targetCompass
    target: hostile
lobbies:
  default:
    type: fixedPhysicalLobby
    join:
    - 773;76;-562;world
    spawn: 769.5;75;-561.5;world;90;0
    start: 761;76;-562;world
    leave: 771;76;-562;world
    default_class:
      name: Balanced
      engine: balancedEngine
      wings: balancedWings
      items:
      - balancedWeapon
      - gun
    items:
      addRocket:
        type: add
        buy_cost: 15
        block: 764;76;-565;world
        items:
        - rocket
      addLauncher:
        type: add
        buy_cost: 10
        block: 766;76;-565;world
        items:
        - launcher
      addCompass:
        type: add
        buy_cost: 5
        block: 768;76;-565;world
        items:
        - radar
      fast:
        name: Fast
        type: replace
        block: 764;76;-559;world
        engine: fastEngine
        wings: lightWings
        items:
        - fastWeapon
        - gun
      balanced:
        name: Balanced
        type: replace
        block: 766;76;-559;world
        engine: balancedEngine
        wings: balancedWings
        items:
        - balancedWeapon
        - gun
      strong:
        name: Strong
        type: replace
        block: 768;76;-559;world
        engine: strongEngine
        wings: heavyWings
        items:
        - strongWeapon
        - gun
    games:
    - default
games:
  default:
    type: teamDeathMatch
    respawn_action: save
    teams:
      blue:
        name: 'Blue'
        location: 766.5;201;-677.5;world;0;0
        color: blue
      red:
        name: 'Red'
        location: 766.5;201;-445.5;world;180;0
        color: red
    money:
      enabled: true
      enemy_hit: 1
      enemy_kill: 5
      friendly_kill: -2
      by_friendly_death: 2
      suicide: -1
