engines:
  balancedEngine:
    type: simpleEngine
    material: sugar cane
    name: '&2Balanced Engine'
    lore:
    - ''
    - '&aHold shift to accelerate.'
    max_speed: 1.5
    acceleration: 0.025
    max_fuel: 750
    consumption: 2
    regeneration: 1
    glow_time: 100
  fastEngine:
    type: simpleEngine
    material: feather
    name: '&2Fast Engine'
    lore:
    - '&aHold shift to accelerate.'
    max_speed: 2.5
    acceleration: 0.01
    max_fuel: 500
    consumption: 2.5
    regeneration: 1.5
    glow_time: 50
  strongEngine:
    type: simpleEngine
    material: wheat
    name: '&2Strong Engine'
    lore:
    - '&aHold shift to accelerate.'
    max_speed: 1
    acceleration: 0.05
    max_fuel: 1500
    consumption: 2
    regeneration: 1
    glow_time: 200
items:
  balancedWeapon:
    type: simpleWeapon
    material: bone
    name: '&4Balanced Weapon'
    lore:
    - '&cLeft click to shoot.'
    entity: small fireball
    slot: 0
    burst_amount: 15
    burst_ticks: 1
    projectile_speed: 5.75
    cooldown: 35
    consumable: false
    only_air: true
    damage: 601
    wings_off: true
    kills_on_ground: false
    physical_damage: 7.5
  strongWeapon:
    type: simpleWeapon
    material: blaze rod
    name: '&4Strong Weapon'
    lore:
    - '&cLeft click to shoot.'
    entity: fireball
    slot: 0
    burst_amount: 10
    burst_ticks: 1
    projectile_speed: 5
    cooldown: 40
    consumable: false
    only_air: true
    damage: 2401
    wings_off: true
    kills_on_ground: true
    physical_damage: 10
  fastWeapon:
    type: simpleWeapon
    material: stick
    name: '&4Fast Weapon'
    lore:
    - '&cLeft click to shoot.'
    entity: snowball
    slot: 0
    burst_amount: 20
    burst_ticks: 1
    projectile_speed: 50
    cooldown: 25
    consumable: false
    only_air: true
    damage: 901
    wings_off: false
    kills_on_ground: false
    physical_damage: 5
  gun:
    type: simpleWeapon
    material: torch
    name: '&4Gun'
    lore:
    - '&cLeft click to shoot.'
    entity: snowball
    slot: 2
    burst_amount: 1
    burst_ticks: 1
    projectile_speed: 5
    cooldown: 5
    consumable: false
    only_air: false
    damage: 1001
    wings_off: false
    kills_on_ground: false
    physical_damage: 5
  rocket:
    type: homingMissile
    material: arrow
    name: '&eRocket'
    lore:
    - '&cLeft click to launch.'
    entity: arrow
    slot: 3
    range: 64
    speed: 3
    life: 400
    maneuverability: 1
    cooldown: 200
    consumable: true
    only_air: true
    damage: 2000
    wings_off: true
    kills_on_ground: false
    physical_damage: 16
wings:
  balancedWings:
    type: simpleWings
    name: '&3Balanced Wings'
    lore:
    - '&bPress space to fly.'
    health: 2400
    regeneration: 0.5
  lightWings:
    type: simpleWings
    name: '&3Light Wings'
    lore:
    - '&bPress space to fly.'
    health: 1800
    regeneration: 0.5
    aerodynamics: 0.0025
    liftingforce: 0.001
  heavyWings:
    type: simpleWings
    name: '&3Heavy Wings'
    lore:
    - '&bPress space to fly.'
    health: 3600
    regeneration: 0.5
    weight: 0.002
    aerodynamics: -0.0025
classes:
  balanced:
    type: fixedClass
    engine: balancedEngine
    items:
    - balancedWeapon
    - gun
    - rocket 2
    wings: balancedWings
  fast:
    type: fixedClass
    engine: fastEngine
    items:
    - fastWeapon
    - gun
    - rocket 2
    wings: lightWings
  strong:
    type: fixedClass
    engine: strongEngine
    items:
    - strongWeapon
    - gun
    - rocket 2
    wings: heavyWings
games:
  default:
    type: simpleGame
    teams:
      blue:
        name: 'Blue'
        location: -82.5;140;249.5;world;0;0
        color: blue
      red:
        name: 'Red'
        location: -82.5;140;377.5;world;180;0
        color: red
    lobby:
      join:
      - -19;64;334;world
      spawn: -22.5;64;334.5;world;90;0
      start: -32;64;334;world
      leave: -21;64;334;world
      choice:
        team:
          red: -28;64;331;world
          blue: -26;64;331;world
        class:
          fast: -25;64;337;world
          balanced: -27;64;337;world
          strong: -29;64;337;world
