engines:
  balancedEngine:
    type: multiplyingEngine
    material: sugar cane
    name: '&2Balanced Engine'
    lore:
    - '&bMedium speed, acceleration and fuel.'
    - '&eHold shift to accelerate.'
    max_speed: 1.5
    acceleration: 0.025
    max_fuel: 750
    consumption: 2
    regeneration: 1
    glow_time: 100
  fastEngine:
    type: multiplyingEngine
    material: feather
    name: '&2Fast Engine'
    lore:
    - '&bHigh maximum speed and fuel regeneration.'
    - '&bLow acceleration and fuel reserves.'
    - '&eHold shift to accelerate.'
    max_speed: 2.5
    acceleration: 0.01
    max_fuel: 500
    consumption: 2.5
    regeneration: 1.5
    glow_time: 50
  strongEngine:
    type: multiplyingEngine
    material: wheat
    name: '&2Strong Engine'
    lore:
    - '&bLow speed and fuel regeneration.'
    - '&bHigh acceleration and fuel reserves.'
    - '&eHold shift to accelerate.'
    max_speed: 1
    acceleration: 0.05
    max_fuel: 1500
    consumption: 2
    regeneration: 1
    glow_time: 200
items:
  balancedWeapon:
    type: machineGun
    material: bone
    name: '&4Balanced Weapon'
    lore:
    - '&bMedium burst length, low damage.'
    - '&bDisables wings.'
    - '&eLeft click to shoot.'
    entity: small fireball
    slot: 0
    burst_amount: 15
    burst_ticks: 1
    projectile_speed: 5.75
    cooldown: 35
    consumable: false
    only_air: true
    damage: 601
    wings_off: true
    kills_on_ground: false
    physical_damage: 7.5
  strongWeapon:
    type: machineGun
    material: blaze rod
    name: '&4Strong Weapon'
    lore:
    - '&bShort burst length, high damage.'
    - '&bDisables wings, kills on ground.'
    - '&eLeft click to shoot.'
    entity: fireball
    slot: 0
    burst_amount: 10
    burst_ticks: 1
    projectile_speed: 5
    cooldown: 40
    consumable: false
    only_air: true
    damage: 2401
    wings_off: true
    kills_on_ground: true
    physical_damage: 10
  fastWeapon:
    type: machineGun
    material: stick
    name: '&4Fast Weapon'
    lore:
    - '&bLong burst length, medium damage.'
    - '&eLeft click to shoot.'
    entity: snowball
    slot: 0
    burst_amount: 20
    burst_ticks: 1
    projectile_speed: 50
    cooldown: 25
    consumable: false
    only_air: true
    damage: 901
    wings_off: false
    kills_on_ground: false
    physical_damage: 5
  gun:
    type: machineGun
    material: torch
    name: '&cGun'
    lore:
    - '&bCan shoot from the ground.'
    - '&eLeft click to shoot.'
    entity: snowball
    slot: 2
    burst_amount: 1
    burst_ticks: 1
    projectile_speed: 5
    cooldown: 5
    consumable: false
    only_air: false
    damage: 1001
    wings_off: false
    kills_on_ground: false
    physical_damage: 5
  strong_rocket:
    type: homingMissile
    material: arrow
    name: '&dStrong Rocket'
    lore:
    - '&bTracks players. Disables wings.'
    - '&bLow speed, high damage.'
    - '&eLeft click to launch.'
    entity: arrow
    slot: 3
    search_range: 64
    search_radius: 0.05
    speed: 1.5
    lifetime: 1000
    maneuverability: 0.25
    cooldown: 200
    consumable: true
    only_air: true
    damage: 4000
    wings_off: true
    kills_on_ground: true
    physical_damage: 20
  balanced_rocket:
    type: homingMissile
    material: arrow
    name: '&dBalanced Rocket'
    lore:
    - '&bTracks players. Disables wings.'
    - '&bMedium speed and damage.'
    - '&eLeft click to launch.'
    entity: arrow
    slot: 3
    search_range: 64
    search_radius: 0.05
    speed: 2
    lifetime: 400
    maneuverability: 0.5
    cooldown: 200
    consumable: true
    only_air: true
    damage: 2000
    wings_off: true
    kills_on_ground: false
    physical_damage: 16
  fast_rocket:
    type: homingMissile
    material: arrow
    name: '&dFast Rocket'
    lore:
    - '&bTracks players. Disables wings.'
    - '&bHigh speed and accuracy.'
    - '&eLeft click to launch.'
    entity: arrow
    slot: 3
    search_range: 64
    search_radius: 0.05
    speed: 3
    lifetime: 200
    maneuverability: 0.75
    cooldown: 200
    consumable: true
    only_air: true
    damage: 0
    wings_off: true
    kills_on_ground: false
    physical_damage: 6
  weak_launcher:
    type: launcher
    material: firework
    name: '&5Weak Launcher'
    lore:
    - '&bLaunches you in the air.'
    - '&bWeak force.'
    - '&eLeft click to use.'
    slot: 4
    speed: 0.75
    cooldown: 100
    consumable: true
    only_air: false
  strong_launcher:
    type: launcher
    material: firework
    name: '&5Strong Launcher'
    lore:
    - '&bLaunches you in the air.'
    - '&bPowerful force.'
    - '&eLeft click to use.'
    slot: 4
    speed: 2
    cooldown: 100
    consumable: true
    only_air: false
  radar:
    type: vanillaItem
    material: compass
    name: '&aRadar'
    lore:
    - '&bShows hostile targets.'
    slot: 8
    passive_effects:
    - radar
effects:
  radar:
    type: targetCompass
    target: hostile
wings:
  balancedWings:
    type: simpleWings
    name: '&3Balanced Wings'
    lore:
    - '&bDefault Elytra fight.'
    - '&bMedium durability.'
    - '&ePress space to fly.'
    health: 2400
    regeneration: 0.5
  lightWings:
    type: simpleWings
    name: '&3Light Wings'
    lore:
    - '&bFast wings with strong lifting force.'
    - '&bQuite fragile.'
    - '&ePress space to fly.'
    health: 1800
    regeneration: 0.5
    aerodynamics: 0.0025
    liftingforce: 0.001
  heavyWings:
    type: simpleWings
    name: '&3Heavy Wings'
    lore:
    - '&bSlow, heavy wings.'
    - '&bVery sturdy.'
    - '&ePress space to fly.'
    health: 3600
    regeneration: 0.5
    weight: 0.002
    aerodynamics: -0.0025
lobbies:
  default:
    type: fixedPhysicalLobby
    join:
    - -19;64;334;world
    spawn: -22.5;63;334.5;world;90;0
    start: -32;64;334;world
    leave: -21;64;334;world
    default_class:
      name: Balanced
      engine: balancedEngine
      items:
      - balancedWeapon
      - gun
      - balanced_rocket 2
      - weak_launcher 3
      - radar
      wings: balancedWings
    items:
      fast:
        name: Fast
        type: clear
        block: -25;64;337;world
        engine: fastEngine
        items:
        - fastWeapon
        - gun
        - fast_rocket 5
        - strong_launcher 3
        - radar
        wings: lightWings
      balanced:
        name: Balanced
        type: clear
        block: -27;64;337;world
        engine: balancedEngine
        items:
        - balancedWeapon
        - gun
        - balanced_rocket 2
        - weak_launcher 3
        - radar
        wings: balancedWings
      strong:
        name: Strong
        type: clear
        block: -29;64;337;world
        engine: strongEngine
        items:
        - strongWeapon
        - gun
        - strong_rocket
        - weak_launcher
        - radar
        wings: heavyWings
games:
  default:
    respawn_action: load
    type: teamDeathMatch
    teams:
      blue:
        name: 'Blue'
        location: -82.5;140;249.5;world;0;0
        color: blue
      red:
        name: 'Red'
        location: -82.5;140;377.5;world;180;0
        color: red
    lobby: default
