name: Flier
main: pl.betoncraft.flier.Flier
description: Elytra fighting minigame
authors: [Co0sh]
version: 0.3.0
commands:
  flier:
    description: Gives you flying items
    usage: /<command>
    permission: flier.items
    aliases: [f, fl]